export {default as HomePage} from './Home'
export {default as ProfilePage} from './Profile'
export {default as DetailPage} from './Detail'
export {default as FavouritePage} from './Favourite'
export {default as LoginPage} from './Login'
export {default as SignUpPage} from './Signup'
export {default as UploadPage} from './Upload'